# Generated by Django 5.1.1 on 2024-11-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
