# Generated by Django 5.1.1 on 2024-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_year_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year_made',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
