# Generated by Django 5.1.1 on 2024-11-26 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_year_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='makes')),
            ],
            options={
                'verbose_name': 'makes',
                'verbose_name_plural': 'make',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
