# Generated by Django 5.1.1 on 2024-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_make_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='make',
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.ManyToManyField(to='shop.make'),
        ),
    ]
