# Generated by Django 5.1.1 on 2024-11-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_make_product_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='make',
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.TextField(blank=True, null=True),
        ),
    ]
