# Generated by Django 5.1.1 on 2024-11-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_make_product_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.make'),
        ),
    ]
