# Generated by Django 5.1.1 on 2024-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
