# Generated by Django 5.1.1 on 2024-11-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='make',
            new_name='model',
        ),
    ]
