# Generated by Django 5.1.1 on 2024-11-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_make_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='make',
        ),
    ]
