# Generated by Django 5.1.1 on 2024-11-26 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
